### ISSUE TITLE
client-user :  Failed to load resource

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#64]
Hello,
   I find a little issue in the page client-user, for example, in example desktop project:

- [ ] 1st. Enter one of your project in client-user,
- [ ] 2nd F12 and refresh, in console: 

![selection_143](https://cloud.githubusercontent.com/assets/16957363/14957970/0dbef340-1080-11e6-88ce-a8db60848fe0.png)

  Is it for the initialization of a project in the 'desktop' mode ?
  That's very kind of you if you can send me some tutorials and explanation of the freemarker files here.  

Thank you.
Regards,
guanji

**Comment by malapert** [comment]
Hi Guanji,

That's not a bug but a feature. Sitools2 is based on a REST architecture.
In a REST architecture, each status means a specific response of an action.
In this case, the client tries to load user preferences. In your case, you
do not have user preferences and the server responds that it cannot find
any user preferences (http status 404 means not found).

Cheers,
Jean-Christophe

**Comment by guanjiwang2016** [comment]
Hi Jean-Christophe,
     Thank you for your reply.
      it is not a bug but for customization.  I found the path definition for the feature in project.js and I can define a user preference in the folder data/userstorage/admin&public/{projectname}
      And can I get an example of the file 'desktop' if it is convenient for you, please?  I think it is text file with window configuration.
   Thank you for your help.

regards,
guanji

**Comment by malapert** [comment]
Hi,

The freemarker can be found in data/freemarker. In the administration page,
you can modify the name of the template to apply.

For instance, the default freemarker should be this one :
https://github.com/SITools2/
<https://github.com/SITools2/SITools2-core/blob/master/data/freemarker/default.html>
SITools2-
<https://github.com/SITools2/SITools2-core/blob/master/data/freemarker/default.html>
core
<https://github.com/SITools2/SITools2-core/blob/master/data/freemarker/default.html>
/blob/master/data/freemarker/
<https://github.com/SITools2/SITools2-core/blob/master/data/freemarker/default.html>
default.html
<https://github.com/SITools2/SITools2-core/blob/master/data/freemarker/default.html>

You should keep the defined ID in the template, excepted for those under
rightPanel. The ID under rightPanel allow you to load the module with this
ID=name_module in the div. In this way, you can load any modules in a div
instead of loading them in the menu.

Cheers

Hi Jean-Christophe,
Thank you for your reply.
it is not a bug but for customization. I found the path definition for the
feature in project.js and I can define a user preference in the folder
data/userstorage/admin&public/{projectname}
And can I get an example of the file 'desktop' if it is convenient for you,
please? I think it is text file with window configuration.
Thank you for your help.

regards,
guanji

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/SITools2/SITools2-core/issues/64#issuecomment-216456376>
