### ISSUE TITLE
probleme affichage liste de pièces jointes en V3.0.1

### ISSUE THREAD

**Issue by acamarasa** [SITools2/SITools2-core#68]
Pour l'application DataQTIS-NG nous avons un converter qui transforme une liste de fichiers en des liens HTML comme suit (extrait d'une trace mise): 
INFOS: Output:
<a href='/sitools/datastorage/user/productsAutres/Posters/10999/Lune/aa.txt' target='_blank'>aa.txt</a><br/><a href='/sitools/datastorage/user/productsAutres/Posters/10999/Lune/aabis.txt' target='_blank'>aabis.txt</a><br/><a href='/sitools/datastorage/user/productsAutres/Posters/10999/Lune/bb.txt' target='_blank'>bb.txt</a><br/><a href='/sitools/datastorage/user/productsAutres/Posters/10999/Lune/cc.txt' target='_blank'>cc.txt</a><br/>

Ce qui permet d’afficher en HTML

Sur l’ancienne version de SiTools2 (V2.4.1) cela s’affiche correctement

![pieces-jointes-env2](https://cloud.githubusercontent.com/assets/20514569/16911258/bfa12c7e-4cdd-11e6-9a89-17d6ca0e2000.jpg)

 Mais avec SiTools2 V3.0.1  les liens vers les pièces jointes sont fait, en cliquant on ouvre bien la pièce mais l’affichage n'est pas satisfaisant.

![pieces-jointes-env3](https://cloud.githubusercontent.com/assets/20514569/16911262/c8b2c0c0-4cdd-11e6-8834-b2f46d5675f7.jpg)

**Comment by mgond** [comment]
Will be fixed in the next release.
In order to fix it for the release v3.0.1 change the following line in _/client-public-3.0/res/css/main.css_
`body,a,p,div,td,input,select,label,th,button,dt,em {
	color : #19191A;
}`
=>
`body,p,div,td,input,select,label,th,button,dt,em {
	color : #19191A;
}`

Basically remove the a in the list of selectors

**Comment by malapert** [comment]
Hello Mathieu,
The problem is not only the color but the ouput itself.
In the previous version of SITools2, we get : aa.txt, aabis.txt, bb.txt, cc.txt. 
In the last version of SITools2, we get  a duplication of the output with these caracters " '> " in more.
I had a look in the converter, I do not see any mistakes !!!

**Comment by mgond** [comment]
Ok, my mistake.
I fixed it last week, there was a problem with the quotes from the converter and the html code produced.
It will be included in the version 3.0.3 which will be released in the next days.

**Comment by DATAQTIS-NG** [comment]
Le problème n'est pas corrigé. Il y a toujours la présence du caractère ">" et le dédoublement des liens
![capture_erreur_pj](https://cloud.githubusercontent.com/assets/13048999/18252211/ae3f7338-738d-11e6-8777-640d206e3fbd.JPG)

**Comment by malapert** [comment]
Already fixed in 3.0.3
