### ISSUE TITLE
[ISSUE] tool bar disappear 

### ISSUE THREAD

**Issue by gjiwang** [SITools2/SITools2-core#85]
Hello,
   The scenario:
    1. Click http://idoc-medoc-test.ias.u-psud.fr/sitools/client-user/index.html?project=Medoc-Solar-Portal
    2. Select 'Search Forms' in the menu then select any Query Form.
    3. Click search
    4. In the result window, the toolbar disappears for the first time but work after re-open the result window. 
   The bug only appears in Firefox but not in Chrome.

Thank you.
regards,
Guanji
 
![selection_291](https://user-images.githubusercontent.com/20924259/27077942-15ac26d4-5032-11e7-98dc-7950d620ac71.jpg)

**Comment by malapert** [comment]
This bugs only happens on firefox

**Comment by mmebsout** [comment]
This bug is due to this.staticToolbar being undefined when the buttons are added to it.

![toolbar1](https://user-images.githubusercontent.com/7287245/33369985-75f2d882-d4f6-11e7-9479-e6d61d0fc58d.png)
![toolbar3](https://user-images.githubusercontent.com/7287245/33370158-08b88054-d4f7-11e7-8c0a-4997ffcd9f91.png)


Chrome is likely to go faster at initiating staticToolbar than Firefox.

TODO : make sure the staticToolbar is defined before adding the buttons.

**Comment by hubertnouhen** [comment]
Fixed in v3.1.1
